[workspace]
members = [
    ".",
    "example"
]

[package]
name = "fast_log"
version = "1.4.16"
description = "Rust async log High-performance asynchronous logging"
readme = "Readme.md"
authors = ["ce <zhuxiujia@qq.com>"]
edition = "2018"
license = "MIT"


[features]
default = ["runtime_cogo"]
gzip = ["flate2"]

runtime_thread = []
runtime_cogo = ["cogo"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = { version = "0.4", features = ["std"] }
crossbeam-utils = "0.8"
crossbeam = "0.8"
crossbeam-channel = "0.5"
parking_lot = "0.11"
cogo = {version = "0.1", optional = true }
once_cell = "1.9"


zip = { version = "0.5", optional = true }
lz4 = { version = "1.23", optional = true }
flate2 = { version = "1.0", optional = true}